server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
  url: jdbc:mysql://192.168.11.120:8066/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root


 mybatis:
   mapperLoctions: classpath:mapper/*.xml
   type-aliases-package: com.taylor.springcloud.entities